server:
  port: 8090

spring:
  datasource:
    username: masubi
    password: Masubi98%
    url: jdbc:mysql://209.97.154.49:3306/primeclimatecare
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      format-sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

logging:
  level:
    root: WARN
